#!/bin/sh

# Placed in /etc/apm/event.d by the chrony package at the instruction of
# the apmd maintainer.  If you don't have apm and don't intend to install
# apmd you may remove it.  It needs to run after 00hwclock but before any
# other scripts.


[ -x /usr/sbin/chronyd ] || exit 0

if [ "$1" = suspend ]; then
	invoke-rc.d chrony stop
elif [ "$1" = standby ]; then
	invoke-rc.d chrony stop
elif [ "$1" = resume ]; then
	invoke-rc.d chrony start
fi
